[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
categories = ["concurrency", "embedded", "no-std"]
description = "Procedural macros of the cortex-m-rtfm crate"
documentation = "https://docs.rs/cortex-m-rtfm-macros"
keywords = ["arm", "cortex-m"]
license = "MIT OR Apache-2.0"
name = "cortex-m-rtfm-macros"
repository = "https://github.com/japaric/cortex-m-rtfm"
version = "0.3.1"

[dependencies]
failure = "0.1.1"
proc-macro2 = "0.4.4"
quote = "0.6.3"
# rtfm-syntax = "0.4.0"
rtfm-syntax = { git = "https://github.com/burrbull/rtfm-syntax", branch = "tq" }
syn = "0.14.1"

[dependencies.either]
version = "1"
default-features = false

[lib]
proc-macro = true

[features]
timer-queue = []